import type { Metadata } from 'next'
import { Geist, Geist_Mono, Inter, JetBrains_Mono } from 'next/font/google'
import Navbar from '@/components/navbar/Navbar'
import './globals.css'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})
const inter = Inter({ variable: '--font-inter', subsets: ['latin'] })
const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})
const jetbrains = JetBrains_Mono({
    variable: '--font-jetbrains',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'SafeLab',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${jetbrains.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                <div className="absolute top-0 left-0 w-full z-50 flex justify-center">
                    <Navbar />
                </div>
                {children}
            </body>
        </html>
    )
}
